### ISSUE TITLE
Create the Readme

### ISSUE THREAD

**Issue by Arturo2R** [Arturo2R/obsidian-vivaldi-notes#2]
Make a beutifull readme with gifs and roadmap

**Comment by bepolymathe** [comment]
Hi @Arturo2R 

Any news for that ? How to install this plugin ? Is not in obsidian repo... 
Thanks ;-)

**Comment by Arturo2R** [comment]
Hi @bepolymathe, I will register the plugin on obsidian. The reason i didn't initially was because I thought the okugin wasn't as useful as I initially thought. But if somebody finds value I will continue improving the plugin. Right now, the plugin can list and search all your Vivaldi notes, and you can click one to create the notes it importa the images, the link and the originally created date.

**Comment by bepolymathe** [comment]
Hi @Arturo2R 

 Thank you for your message.  I think it's a very useful plugin! 
 Initially, I was looking for something like "send to obsidian" in the vivaldi/chrome add-ons.  But I think that Vivaldi's notes system is quite practical, especially thanks to the screenshots.  So I think other uses might be of interest if you put it on the Obsidian store. 
 Have a good day.

**Comment by Arturo2R** [comment]
Hi @bepolymathe  i have submited the plugin for release in Obsidian. Meanwhile you can use the plugin using BRAT and adding Arturo2r/obsidian-vivaldi-notes

**Comment by bepolymathe** [comment]
Hi, 

I tried on a another machine with BRAT but there is a problem. 

![image](https://github.com/Arturo2R/obsidian-vivaldi-notes/assets/29939805/95b44694-d06e-40d7-b9fb-01a2e2473198)

**Comment by bepolymathe** [comment]
I can't install this plugin ¯\_(ツ)_/¯
